<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Google.Apis.Sheets.v4" Version="1.75.0.4178" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Sirkadiyen.Application/Sirkadiyen.Application.csproj" />
    <ProjectReference Include="../Sirkadiyen.Contracts/Sirkadiyen.Contracts.csproj" />
    <ProjectReference Include="../Sirkadiyen.Domain/Sirkadiyen.Domain.csproj" />
  </ItemGroup>
</Project>
