// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sirkadiyen.Infrastructure.Persistence;

#nullable disable

namespace Sirkadiyen.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SirkadiyenDbContext))]
    [Migration("20260723200128_AddStudentProfiles")]
    partial class AddStudentProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sirkadiyen")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sirkadiyen.Domain.Identity.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("GoogleSubject")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastSignedInAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.HasIndex("LastSignedInAtUtc");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.ToTable("users", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_users_role", "\"Role\" IN ('User', 'SuperAdmin')");

                            t.HasCheckConstraint("ck_users_verified_email", "\"IsEmailVerified\" = TRUE");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Licensing.License", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHash")
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("RedeemedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RedeemedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("RevocationReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid?>("RevokedByUserId")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("RedeemedByUserId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'Redeemed'");

                    b.HasIndex("RevokedByUserId");

                    b.HasIndex("Status");

                    b.ToTable("licenses", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_licenses_code_hash", "(\"Kind\" = 'Code' AND octet_length(\"CodeHash\") = 32)\nOR (\"Kind\" = 'Manual' AND \"CodeHash\" IS NULL)");

                            t.HasCheckConstraint("ck_licenses_expiration", "\"ExpiresAtUtc\" IS NULL OR \"ExpiresAtUtc\" > \"CreatedAtUtc\"");

                            t.HasCheckConstraint("ck_licenses_kind", "\"Kind\" IN ('Code', 'Manual')");

                            t.HasCheckConstraint("ck_licenses_redemption", "(\"RedeemedByUserId\" IS NULL) = (\"RedeemedAtUtc\" IS NULL)\nAND (\"Status\" <> 'Redeemed'\n     OR (\"RedeemedByUserId\" IS NOT NULL AND \"RedeemedAtUtc\" IS NOT NULL))\nAND (\"Status\" NOT IN ('Active', 'Expired')\n     OR \"RedeemedByUserId\" IS NULL)");

                            t.HasCheckConstraint("ck_licenses_revocation", "(\"Status\" = 'Revoked'\n AND \"RevokedByUserId\" IS NOT NULL\n AND \"RevokedByEmail\" IS NOT NULL\n AND \"RevocationReason\" IS NOT NULL\n AND \"RevokedAtUtc\" IS NOT NULL)\nOR\n(\"Status\" <> 'Revoked'\n AND \"RevokedByUserId\" IS NULL\n AND \"RevokedByEmail\" IS NULL\n AND \"RevocationReason\" IS NULL\n AND \"RevokedAtUtc\" IS NULL)");

                            t.HasCheckConstraint("ck_licenses_status", "\"Status\" IN ('Active', 'Redeemed', 'Revoked', 'Expired')");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Licensing.LicenseAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ActorEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LicenseId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("LicenseId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("license_audits", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_license_audits_action", "\"Action\" IN ('Created', 'Redeemed', 'ManuallyActivated', 'Revoked', 'Expired')");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Operations.OperationalFreezeAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<int>("OperationalFreezeControlId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAtUtc");

                    b.HasIndex("OperationalFreezeControlId");

                    b.ToTable("operational_freeze_audits", "sirkadiyen");
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Operations.OperationalFreezeControl", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsFrozen")
                        .HasColumnType("boolean");

                    b.Property<string>("Reason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("operational_freeze_control", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_operational_freeze_control_singleton", "\"Id\" = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsFrozen = false
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleDiffing.ScheduleDiff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmbiguousCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentRecordCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CurrentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("DeletedCount")
                        .HasColumnType("integer");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PreviousRecordCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviousRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReleasedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("ScheduleSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRevisionId")
                        .IsUnique();

                    b.HasIndex("PreviousRevisionId");

                    b.HasIndex("ScheduleSourceId");

                    b.HasIndex("State", "CreatedAtUtc");

                    b.ToTable("schedule_diffs", "sirkadiyen");
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleDiffing.ScheduleDiffEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("CurrentRecordId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DepartmentScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal?>("InstructorScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal?>("MatchScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid?>("PreviousRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleDiffId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TitleScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRecordId");

                    b.HasIndex("PreviousRecordId");

                    b.HasIndex("ScheduleDiffId", "Change");

                    b.HasIndex("ScheduleDiffId", "CurrentRecordId")
                        .IsUnique();

                    b.HasIndex("ScheduleDiffId", "PreviousRecordId")
                        .IsUnique();

                    b.ToTable("schedule_diff_entries", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_diff_entries_record_presence", "\"PreviousRecordId\" IS NOT NULL OR \"CurrentRecordId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleIngestion.SourceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CellCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DiagnosticCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalSnapshotId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PayloadPrunedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ScheduleSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SpreadsheetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("WorksheetCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "AcquiredAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("SourceId", "ContentHash");

                    b.HasIndex("ScheduleSourceId", "AcademicYear", "AcquiredAtUtc");

                    b.ToTable("source_snapshots", "sirkadiyen");
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleParsing.ParseRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("LastStaleRecoveryAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParserProfile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParserProfileVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Response")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SourceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceSnapshotId", "ParserProfile", "ParserProfileVersion")
                        .IsUnique();

                    b.ToTable("parse_runs", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_parse_runs_attempt_count", "\"AttemptCount\" > 0");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.SchedulePublication.CanonicalScheduleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AudienceScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("AudienceSelectors")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ClassYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CurriculumBlock")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Departments")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<TimeOnly?>("EndLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Instructor")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAllDay")
                        .HasColumnType("boolean");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NormalizedCourseIdentity")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProgramLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ScheduleRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StableIdentity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly?>("StartLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleRevisionId", "CandidateId")
                        .IsUnique();

                    b.HasIndex("ScheduleRevisionId", "LocalDate");

                    b.HasIndex("ScheduleRevisionId", "StableIdentity")
                        .IsUnique();

                    b.HasIndex("SourceId", "ClassYear", "ProgramLanguage", "LocalDate");

                    b.ToTable("canonical_schedule_records", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_canonical_schedule_records_schedule_shape", "(\"IsAllDay\" AND \"StartLocalTime\" IS NULL AND \"EndLocalTime\" IS NULL)\nOR (NOT \"IsAllDay\"\n    AND \"StartLocalTime\" IS NOT NULL\n    AND \"EndLocalTime\" IS NOT NULL\n    AND \"EndLocalTime\" > \"StartLocalTime\")");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.SchedulePublication.RevisionValidationFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AffectedRecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("ScheduleRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleRevisionId", "CreatedAtUtc");

                    b.ToTable("revision_validation_findings", "sirkadiyen");
                });

            modelBuilder.Entity("Sirkadiyen.Domain.SchedulePublication.ScheduleRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("ScheduleSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StateReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersededByRevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParseRunId");

                    b.HasIndex("ScheduleSourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_revisions_one_published_per_source")
                        .HasFilter("\"State\" = 'Published'");

                    b.HasIndex("ScheduleSourceId", "CreatedAtUtc");

                    b.HasIndex("State", "CreatedAtUtc");

                    b.ToTable("schedule_revisions", "sirkadiyen");
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleSources.ScheduleSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ClassYear")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DocumentFormat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPollingEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastPolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParserProfile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParserProfileVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProgramLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long?>("SheetGid")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SupportedAudienceSelectors")
                        .HasColumnType("jsonb");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("IsPollingEnabled")
                        .HasFilter("\"IsPollingEnabled\"");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("schedule_sources", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_sources_class_year", "\"ClassYear\" BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.StudentProfiles.StudentProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ClassYear")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProgramLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("SelectorSchemaVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Selectors")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("student_profiles", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_student_profiles_class_year", "\"ClassYear\" BETWEEN 1 AND 6");

                            t.HasCheckConstraint("ck_student_profiles_program_language", "\"ProgramLanguage\" IN ('Turkish', 'English')");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Licensing.License", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sirkadiyen.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RedeemedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sirkadiyen.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("RevokedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Licensing.LicenseAudit", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sirkadiyen.Domain.Licensing.License", null)
                        .WithMany()
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Operations.OperationalFreezeAudit", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Operations.OperationalFreezeControl", null)
                        .WithMany()
                        .HasForeignKey("OperationalFreezeControlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleDiffing.ScheduleDiff", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.SchedulePublication.ScheduleRevision", null)
                        .WithMany()
                        .HasForeignKey("CurrentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sirkadiyen.Domain.SchedulePublication.ScheduleRevision", null)
                        .WithMany()
                        .HasForeignKey("PreviousRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sirkadiyen.Domain.ScheduleSources.ScheduleSource", null)
                        .WithMany()
                        .HasForeignKey("ScheduleSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleDiffing.ScheduleDiffEntry", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.SchedulePublication.CanonicalScheduleRecord", null)
                        .WithMany()
                        .HasForeignKey("CurrentRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sirkadiyen.Domain.SchedulePublication.CanonicalScheduleRecord", null)
                        .WithMany()
                        .HasForeignKey("PreviousRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sirkadiyen.Domain.ScheduleDiffing.ScheduleDiff", null)
                        .WithMany("Entries")
                        .HasForeignKey("ScheduleDiffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleIngestion.SourceSnapshot", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.ScheduleSources.ScheduleSource", null)
                        .WithMany()
                        .HasForeignKey("ScheduleSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleParsing.ParseRun", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.ScheduleIngestion.SourceSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SourceSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.SchedulePublication.CanonicalScheduleRecord", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.SchedulePublication.ScheduleRevision", null)
                        .WithMany()
                        .HasForeignKey("ScheduleRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.SchedulePublication.RevisionValidationFinding", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.SchedulePublication.ScheduleRevision", null)
                        .WithMany()
                        .HasForeignKey("ScheduleRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.SchedulePublication.ScheduleRevision", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.ScheduleParsing.ParseRun", null)
                        .WithMany()
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sirkadiyen.Domain.ScheduleSources.ScheduleSource", null)
                        .WithMany()
                        .HasForeignKey("ScheduleSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.StudentProfiles.StudentProfile", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Identity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.ScheduleDiffing.ScheduleDiff", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
