// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sirkadiyen.Infrastructure.Persistence;

#nullable disable

namespace Sirkadiyen.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(SirkadiyenDbContext))]
    [Migration("20260722190232_AddScheduleDiffRelease")]
    partial class AddScheduleDiffRelease
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("sirkadiyen")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Diffing.ScheduleDiff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AmbiguousCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedCount")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentRecordCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("CurrentRevisionId")
                        .HasColumnType("uuid");

                    b.Property<int>("DeletedCount")
                        .HasColumnType("integer");

                    b.Property<string>("HoldReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("PreviousRecordCount")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PreviousRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReleaseReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ReleasedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReleasedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("ScheduleSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("UnchangedCount")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRevisionId")
                        .IsUnique();

                    b.HasIndex("PreviousRevisionId");

                    b.HasIndex("ScheduleSourceId");

                    b.HasIndex("State", "CreatedAtUtc");

                    b.ToTable("schedule_diffs", "sirkadiyen");
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Diffing.ScheduleDiffEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Change")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid?>("CurrentRecordId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("DepartmentScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<decimal?>("InstructorScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<string>("Match")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<decimal?>("MatchScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<Guid?>("PreviousRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScheduleDiffId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("TitleScore")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentRecordId");

                    b.HasIndex("PreviousRecordId");

                    b.HasIndex("ScheduleDiffId", "Change");

                    b.HasIndex("ScheduleDiffId", "CurrentRecordId")
                        .IsUnique();

                    b.HasIndex("ScheduleDiffId", "PreviousRecordId")
                        .IsUnique();

                    b.ToTable("schedule_diff_entries", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_diff_entries_record_presence", "\"PreviousRecordId\" IS NOT NULL OR \"CurrentRecordId\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Ingestion.SourceSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("AcquiredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CellCount")
                        .HasColumnType("integer");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ContractVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DiagnosticCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExternalSnapshotId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ScheduleSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SpreadsheetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("WorksheetCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleSourceId");

                    b.HasIndex("SourceId", "AcquiredAtUtc")
                        .IsDescending(false, true);

                    b.HasIndex("SourceId", "ContentHash");

                    b.ToTable("source_snapshots", "sirkadiyen");
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Parsing.ParseRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<int>("CandidateCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ParserProfile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParserProfileVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Response")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("SourceSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceSnapshotId", "ParserProfile", "ParserProfileVersion")
                        .IsUnique();

                    b.ToTable("parse_runs", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_parse_runs_attempt_count", "\"AttemptCount\" > 0");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Publication.CanonicalScheduleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("AudienceScope")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("AudienceSelectors")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("CandidateId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("ClassYear")
                        .HasColumnType("integer");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Department")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DisplayTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<TimeOnly>("EndLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Instructor")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateOnly>("LocalDate")
                        .HasColumnType("date");

                    b.Property<string>("Location")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NormalizedCourseIdentity")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProgramLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RecordStatus")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("ScheduleRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StableIdentity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly>("StartLocalTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleRevisionId", "CandidateId")
                        .IsUnique();

                    b.HasIndex("ScheduleRevisionId", "LocalDate");

                    b.HasIndex("ScheduleRevisionId", "StableIdentity")
                        .IsUnique();

                    b.HasIndex("SourceId", "ClassYear", "ProgramLanguage", "LocalDate");

                    b.ToTable("canonical_schedule_records", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_canonical_schedule_records_time_order", "\"EndLocalTime\" > \"StartLocalTime\"");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Publication.RevisionValidationFinding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AffectedRecordCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Rule")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid>("ScheduleRevisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleRevisionId", "CreatedAtUtc");

                    b.ToTable("revision_validation_findings", "sirkadiyen");
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Publication.ScheduleRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApprovalReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("ApprovedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParseRunId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RecordCount")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("ScheduleSourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("StateReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset?>("SupersededAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SupersededByRevisionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParseRunId");

                    b.HasIndex("ScheduleSourceId")
                        .IsUnique()
                        .HasDatabaseName("ix_schedule_revisions_one_published_per_source")
                        .HasFilter("\"State\" = 'Published'");

                    b.HasIndex("ScheduleSourceId", "CreatedAtUtc");

                    b.HasIndex("State", "CreatedAtUtc");

                    b.ToTable("schedule_revisions", "sirkadiyen");
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Sources.ScheduleSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcademicYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("ClassYear")
                        .HasColumnType("integer");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DocumentFormat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsPollingEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastChangedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastPolledAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ParserProfile")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ParserProfileVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ProgramLanguage")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<long?>("SheetGid")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SourceUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("SupportedAudienceSelectors")
                        .HasColumnType("jsonb");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.HasKey("Id");

                    b.HasIndex("IsPollingEnabled")
                        .HasFilter("\"IsPollingEnabled\"");

                    b.HasIndex("SourceId")
                        .IsUnique();

                    b.ToTable("schedule_sources", "sirkadiyen", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_sources_class_year", "\"ClassYear\" BETWEEN 1 AND 6");
                        });
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Diffing.ScheduleDiff", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Scheduling.Publication.ScheduleRevision", null)
                        .WithMany()
                        .HasForeignKey("CurrentRevisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sirkadiyen.Domain.Scheduling.Publication.ScheduleRevision", null)
                        .WithMany()
                        .HasForeignKey("PreviousRevisionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sirkadiyen.Domain.Scheduling.Sources.ScheduleSource", null)
                        .WithMany()
                        .HasForeignKey("ScheduleSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Diffing.ScheduleDiffEntry", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Scheduling.Publication.CanonicalScheduleRecord", null)
                        .WithMany()
                        .HasForeignKey("CurrentRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sirkadiyen.Domain.Scheduling.Publication.CanonicalScheduleRecord", null)
                        .WithMany()
                        .HasForeignKey("PreviousRecordId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sirkadiyen.Domain.Scheduling.Diffing.ScheduleDiff", null)
                        .WithMany("Entries")
                        .HasForeignKey("ScheduleDiffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Ingestion.SourceSnapshot", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Scheduling.Sources.ScheduleSource", null)
                        .WithMany()
                        .HasForeignKey("ScheduleSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Parsing.ParseRun", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Scheduling.Ingestion.SourceSnapshot", null)
                        .WithMany()
                        .HasForeignKey("SourceSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Publication.CanonicalScheduleRecord", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Scheduling.Publication.ScheduleRevision", null)
                        .WithMany()
                        .HasForeignKey("ScheduleRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Publication.RevisionValidationFinding", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Scheduling.Publication.ScheduleRevision", null)
                        .WithMany()
                        .HasForeignKey("ScheduleRevisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Publication.ScheduleRevision", b =>
                {
                    b.HasOne("Sirkadiyen.Domain.Scheduling.Parsing.ParseRun", null)
                        .WithMany()
                        .HasForeignKey("ParseRunId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sirkadiyen.Domain.Scheduling.Sources.ScheduleSource", null)
                        .WithMany()
                        .HasForeignKey("ScheduleSourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sirkadiyen.Domain.Scheduling.Diffing.ScheduleDiff", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
