'use client';

import { useCallback, useEffect, useState } from 'react';
import { ApiError, getAdminLicense, getAdminUser, listAdminLicenses, listAdminUsers, revokeLicense } from '@/lib/api';
import { DetailDrawer, LoadState, Pager, Tabs, formatDateTime, statusBadge } from '@/components/AdminData';
import { LicenseAdministration } from '@/components/LicenseAdministration';
import type { AdminLicenseDetail, AdminLicenseListItem, AdminUserDetailResponse, AdminUserListItem, LicenseKind, LicenseStatus, PagedResult, UserRole } from '@/lib/types';

export function AdminUserDirectory() {
  const [tab, setTab] = useState('users');
  return <><Tabs value={tab} onChange={setTab} items={[{ value: 'users', label: 'Kullanıcılar' }, { value: 'licenses', label: 'Lisanslar' }]} />{tab === 'users' ? <Users /> : <Licenses />}</>;
}

function Users() {
  const [searchInput, setSearchInput] = useState(''); const [search, setSearch] = useState('');
  const [role, setRole] = useState<UserRole | ''>(''); const [page, setPage] = useState(1);
  const [data, setData] = useState<PagedResult<AdminUserListItem> | null>(null);
  const [selected, setSelected] = useState<AdminUserDetailResponse | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const timer = window.setTimeout(() => { setSearch(searchInput.trim()); setPage(1); }, 300); return () => window.clearTimeout(timer); }, [searchInput]);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setData(await listAdminUsers({ search, role: role || undefined, page, pageSize: 50 })); } catch (e) { setError(e instanceof ApiError ? e.message : 'Kullanıcılar alınamadı.'); } finally { setLoading(false); } }, [search, role, page]);
  useEffect(() => { void load(); }, [load]);
  async function open(user: AdminUserListItem) { setSelected(null); try { setSelected(await getAdminUser(user.id)); } catch (e) { setError(e instanceof ApiError ? e.message : 'Kullanıcı detayı alınamadı.'); } }
  return <section className="card admin-workspace-card">
    <div className="cluster" style={{ gap: 10, marginBottom: 16 }}><input className="text-input" value={searchInput} onChange={(e) => setSearchInput(e.target.value)} placeholder="E-posta ara…" aria-label="Kullanıcı e-postası ara" /><select className="select-input" value={role} onChange={(e) => { setRole(e.target.value); setPage(1); }} aria-label="Rol filtresi"><option value="">Tüm roller</option><option value="Student">Student</option><option value="SuperAdmin">SuperAdmin</option></select></div>
    <LoadState loading={loading} error={error} empty={!loading && data?.items.length === 0} onRetry={() => void load()} />
    {!loading && data && data.items.length > 0 && <><div className="table-wrap"><table className="data-table data-table--stack"><thead><tr><th>Kullanıcı</th><th>Rol</th><th>Lisans</th><th>Profil</th><th>Son giriş</th></tr></thead><tbody>{data.items.map((user) => <tr key={user.id} onClick={() => void open(user)} style={{ cursor: 'pointer' }}><td data-label="Kullanıcı"><strong>{user.displayName ?? '—'}</strong><small className="muted" style={{ display: 'block' }}>{user.email}</small></td><td data-label="Rol">{user.role}</td><td data-label="Lisans"><span className={`badge ${statusBadge(user.licenseState)}`}>{user.licenseState}</span></td><td data-label="Profil">{user.hasProfile ? 'Tamamlandı' : 'Eksik'}</td><td data-label="Son giriş">{formatDateTime(user.lastSignedInAtUtc)}</td></tr>)}</tbody></table></div><Pager page={data.page} totalPages={data.totalPages} totalCount={data.totalCount} onChange={setPage} /></>}
    {selected && <DetailDrawer title={selected.user.summary.displayName ?? selected.user.summary.email} subtitle={selected.user.summary.email} onClose={() => setSelected(null)}><Detail title="Hesap"><Row label="Onboarding" value={selected.onboardingState} /><Row label="Lisans" value={selected.user.summary.licenseState} /><Row label="Yönetilen etkinlik" value={String(selected.user.managedEventCount)} /></Detail>{selected.user.profile ? <Detail title="Akademik profil"><Row label="Öğrenci no" value={selected.user.profile.studentNumber} /><Row label="Dönem" value={String(selected.user.profile.classYear)} /><Row label="Program" value={selected.user.profile.programLanguage} />{Object.entries(selected.user.profile.selectors).map(([k, v]) => <Row key={k} label={k} value={v} />)}</Detail> : <Detail title="Akademik profil"><p className="muted">Profil henüz tamamlanmadı.</p></Detail>}<Detail title="Lisans geçmişi">{selected.user.licenses.length ? selected.user.licenses.map((item) => <p key={item.licenseId}><span className={`badge ${statusBadge(item.status)}`}>{item.status}</span> <span className="mono">{item.licenseId}</span><small className="muted" style={{ display: 'block' }}>{formatDateTime(item.createdAtUtc)}</small></p>) : <p className="muted">Lisans kaydı yok.</p>}</Detail><Detail title="Son girişler">{selected.recentSignIns.length ? selected.recentSignIns.map((event) => <p key={event.id}>{formatDateTime(event.occurredAtUtc)} · {event.maskedIp ?? 'IP yok'}</p>) : <p className="muted">Giriş kaydı yok.</p>}</Detail></DetailDrawer>}
  </section>;
}

function Licenses() {
  const [status, setStatus] = useState<LicenseStatus | ''>(''); const [kind, setKind] = useState<LicenseKind | ''>(''); const [page, setPage] = useState(1);
  const [data, setData] = useState<PagedResult<AdminLicenseListItem> | null>(null); const [detail, setDetail] = useState<AdminLicenseDetail | null>(null);
  const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [reason, setReason] = useState(''); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setData(await listAdminLicenses({ status: status || undefined, kind: kind || undefined, page, pageSize: 50 })); } catch (e) { setError(e instanceof ApiError ? e.message : 'Lisanslar alınamadı.'); } finally { setLoading(false); } }, [status, kind, page]);
  useEffect(() => { void load(); }, [load]);
  async function open(item: AdminLicenseListItem) { try { setDetail(await getAdminLicense(item.licenseId)); setReason(''); } catch (e) { setError(e instanceof ApiError ? e.message : 'Lisans detayı alınamadı.'); } }
  async function revoke() { if (!detail || !reason.trim()) return; setBusy(true); try { await revokeLicense(detail.summary.licenseId, reason.trim()); setDetail(await getAdminLicense(detail.summary.licenseId)); setReason(''); await load(); } catch (e) { setError(e instanceof ApiError ? e.message : 'Lisans iptal edilemedi.'); } finally { setBusy(false); } }
  return <div className="stack" style={{ gap: 18 }}><LicenseAdministration onCreated={() => void load()} /><section className="card admin-workspace-card"><div className="cluster" style={{ gap: 10, marginBottom: 16 }}><select className="select-input" value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }}><option value="">Tüm durumlar</option>{['Created','Active','Redeemed','Revoked','Expired'].map((v) => <option key={v}>{v}</option>)}</select><select className="select-input" value={kind} onChange={(e) => { setKind(e.target.value); setPage(1); }}><option value="">Tüm türler</option><option>Code</option><option>Manual</option></select></div><LoadState loading={loading} error={error} empty={!loading && data?.items.length === 0} onRetry={() => void load()} />{!loading && data && data.items.length > 0 && <><div className="table-wrap"><table className="data-table"><thead><tr><th>Kimlik</th><th>Tür</th><th>Durum</th><th>Oluşturan</th><th>Oluşturma</th></tr></thead><tbody>{data.items.map((item) => <tr key={item.licenseId} onClick={() => void open(item)} style={{ cursor: 'pointer' }}><td className="mono">{item.licenseId}</td><td>{item.kind}</td><td><span className={`badge ${statusBadge(item.status)}`}>{item.status}</span></td><td>{item.createdByEmail}</td><td>{formatDateTime(item.createdAtUtc)}</td></tr>)}</tbody></table></div><Pager page={data.page} totalPages={data.totalPages} totalCount={data.totalCount} onChange={setPage} /></>}{detail && <DetailDrawer title="Lisans detayı" subtitle={detail.summary.licenseId} onClose={() => setDetail(null)}><Detail title="Durum"><Row label="Tür" value={detail.summary.kind} /><Row label="Durum" value={detail.summary.status} /><Row label="Oluşturan" value={detail.summary.createdByEmail} /><Row label="Not" value={detail.summary.notes ?? '—'} /></Detail><Detail title="Denetim geçmişi">{detail.audit.map((entry, i) => <p key={`${entry.occurredAtUtc}-${i}`}><strong>{entry.action}</strong> · {entry.actorEmail}<small className="muted" style={{ display: 'block' }}>{entry.reason || 'Gerekçe yok'} · {formatDateTime(entry.occurredAtUtc)}</small></p>)}</Detail>{detail.summary.status !== 'Revoked' && <Detail title="Lisansı iptal et"><p className="muted">Takvim verileri korunur; gelecekteki senkronizasyon durur.</p><textarea className="text-input" value={reason} onChange={(e) => setReason(e.target.value)} placeholder="Zorunlu gerekçe" style={{ margin: '10px 0' }} /><button className="btn btn-danger" type="button" disabled={busy || !reason.trim()} onClick={() => void revoke()}>{busy ? 'İptal ediliyor…' : 'Seçili lisansı iptal et'}</button></Detail>}</DetailDrawer>}</section></div>;
}

function Detail({ title, children }: { title: string; children: React.ReactNode }) { return <section style={{ padding: '14px 0', borderBottom: '1px solid var(--border)' }}><h3 style={{ fontSize: 13, textTransform: 'uppercase', color: 'var(--ink-70)' }}>{title}</h3><div style={{ marginTop: 8 }}>{children}</div></section>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="summary-row"><span className="muted">{label}</span><strong>{value}</strong></div>; }
